{{ config(materialized='view', schema='gold', alias="Sales agreement line fact") }}

SELECT  t.SalesAgreementLineKey  AS [Sales agreement line key]
    , t.AgreementStateKey      AS [Agreement state key]
    , t.CustomerKey            AS [Customer key]
    , t.EffectiveDateKey       AS [Effective date key]
    , t.ExpirationDateKey      AS [Expiration date key]
    , t.LineEffectiveDateKey   AS [Line effective date key]
    , t.LineExpirationDateKey  AS [Line expiration date key]
    , t.InventorySiteKey       AS [Inventory site key]
    , t.LegalEntityKey         AS [Legal entity key]
    , t.ProductKey             AS [Product key]
    , t.WarehouseKey           AS [Warehouse key]
    , CAST(1 AS INT)           AS [Sales agreement line count]
    , t.AgreementQuantity      AS [Agreement quantity]
      , t.AgreementQuantity_LB * 1 AS [Agreement LB], t.AgreementQuantity_LB * 0.01 AS [Agreement CWT], t.AgreementQuantity_LB * 0.0005 AS [Agreement TON]
      , t.AgreementQuantity_FT * 1 AS [Agreement FT], t.AgreementQuantity_FT * 12 AS [Agreement IN]
      , t.AgreementQuantity_PC * 1 AS [Agreement PC]
      , t.AgreementQuantity_SQIN * 1 AS [Agreement SQIN]
    , t.BaseAmount             AS [Base amount]
    , t.BaseAmount_TransCur    AS [Base amount in trans currency]
    , t.BaseUnitPrice          AS [Base unit price]
    , t.BaseUnitPrice_TransCur AS [Base unit price in trans currency]
    , t.InvoicedQuantity       AS [Invoice quantity]
      , t.InvoicedQuantity_LB * 1 AS [Invoice LB], t.InvoicedQuantity_LB * 0.01 AS [Invoice CWT], t.InvoicedQuantity_LB * 0.0005 AS [Invoice TON]
      , t.InvoicedQuantity_FT * 1 AS [Invoice FT], t.InvoicedQuantity_FT * 12 AS [Invoice IN]
      , t.InvoicedQuantity_PC * 1 AS [Invoice PC]
      , t.InvoicedQuantity_SQIN * 1 AS [Invoice SQIN]
    , t.ReceivedQuantity       AS [Receive quantity]    
    , t.ReceivedQuantity_LB * 1 AS [Receive LB], t.ReceivedQuantity_LB * 0.01 AS [Receive CWT], t.ReceivedQuantity_LB * 0.0005 AS [Receive TON]
      , t.ReceivedQuantity_FT * 1 AS [Receive FT], t.ReceivedQuantity_FT * 12 AS [Receive IN]
      , t.ReceivedQuantity_PC * 1 AS [Receive PC]
      , t.ReceivedQuantity_SQIN * 1 AS [Receive SQIN]
    , t.ReleasedQuantity       AS [Release quantity]
    , t.ReleasedQuantity_LB * 1 AS [Release LB], t.ReleasedQuantity_LB * 0.01 AS [Release CWT], t.ReleasedQuantity_LB * 0.0005 AS [Release TON]
      , t.ReleasedQuantity_FT * 1 AS [Release FT], t.ReleasedQuantity_FT * 12 AS [Release IN]
      , t.ReleasedQuantity_PC * 1 AS [Release PC]
      , t.ReleasedQuantity_SQIN * 1 AS [Release SQIN]
    , t.RemainingQuantity      AS [Remain quantity]
    , t.RemainingQuantity_LB * 1 AS [Remain LB], t.RemainingQuantity_LB * 0.01 AS [Remain CWT], t.RemainingQuantity_LB * 0.0005 AS [Remain TON]
      , t.RemainingQuantity_FT * 1 AS [Remain FT], t.RemainingQuantity_FT * 12 AS [Remain IN]
      , t.RemainingQuantity_PC * 1 AS [Remain PC]
      , t.RemainingQuantity_SQIN * 1 AS [Remain SQIN]
      , t.TotalAmount            AS [Total amount]
    , t.TotalAmount_TransCur   AS [Total amount in trans currency]
   , t.totalprice              AS [Total price]
   , t.totalprice_transcur     AS [Total price in trans currency]
  FROM {{ ref("d365cma_salesagreementline_f") }} t;
