{{ config(materialized='view', schema='gold', alias="Asset functional location") }}

SELECT  t.AssetFunctionalLocationKey       AS [Asset functional location key]
    , NULLIF(t.FunctionalLocationID, '') AS [Functional location ID]
    , NULLIF(t.FunctionalLocation, '')   AS [Functional location name]
    , NULLIF(t.Level1ID, '')             AS [Location level 1 ID]
    , NULLIF(t.Level2ID, '')             AS [Location level 2 ID]
    , NULLIF(t.Level3ID, '')             AS [Location level 3 ID]
    , NULLIF(t.Level4ID, '')             AS [Location level 4 ID]
    , NULLIF(t.Level5ID, '')             AS [Location level 5 ID]
    , NULLIF(t.Level6ID, '')             AS [Location level 6 ID]
    , NULLIF(t.Level7ID, '')             AS [Location level 7 ID]
    , NULLIF(t.Level8ID, '')             AS [Location level 8 ID]
    , NULLIF(t.Level9ID, '')             AS [Location level 9 ID]
    , NULLIF(t.Level1, '')               AS [Location level 1]
    , NULLIF(t.Level2, '')               AS [Location level 2]
    , NULLIF(t.Level3, '')               AS [Location level 3]
    , NULLIF(t.Level4, '')               AS [Location level 4]
    , NULLIF(t.Level5, '')               AS [Location level 5]
    , NULLIF(t.Level6, '')               AS [Location level 6]
    , NULLIF(t.Level7, '')               AS [Location level 7]
    , NULLIF(t.Level8, '')               AS [Location level 8]
    , NULLIF(t.Level9, '')               AS [Location level 9]
  FROM {{ ref("d365cma_assetfunctionallocation_d") }} t ;
