{{ config(materialized='view', schema='gold', alias="Inventory on-hand fact") }}

SELECT  InventoryOnHandKey                                AS [Inventory on-hand key]
    , t.AgingMasterTagKey                                    AS [Aging master tag key]
    , t.AgingTagKey                                          AS [Aging tag key]
    , t.LatestWarehouseKey                                   AS [Latest warehouse key]
    , t.LatestWarehouseLocationKey                           AS [Latest warehouse location key]
    , t.LegalEntityKey                                       AS [Legal entity key]
    , t.LicensePlateKey                                      AS [License plate key]
    , t.InventorySourceKey                                   AS [Inventory source key]
    , t.InventoryTransStatusKey                              AS [Inventory trans status key]
    , t.MasterProductKey                                     AS [Master product key]
    , t.MasterTagKey                                         AS [Master tag key]
    , t.ParentTagProductKey                                  AS [Parent tag product key]
    , t.ParentTagKey                                         AS [Parent tag key]
    , t.ProductKey                                           AS [Product key]
    , t.PurchaseOrderLineKey                                 AS [Purchase order line key]
    , t.ReceivedDateKey                                      AS [Received date key]
    , t.SalesOrderLineKey                                    AS [Sales order line key]
    , t.SiteKey                                              AS [Site key]
    , t.TagKey                                               AS [Tag key]
    , t.CostingUOMKey                                        AS [Costing UOM key]
    , t.VendorKey                                            AS [Vendor key]
    , t.WarehouseKey                                         AS [Warehouse key]
    , t.WarehouseLocationKey                                 AS [Warehouse location key]
    , t.AverageUnitCost                                      AS [Average unit cost]
    , t.ArrivedQuantity                                      AS [Arrived quantity]
    , t.ArrivedQuantity_FT * 1 AS [Arrived FT], t.ArrivedQuantity_FT * 12 AS [Arrived IN]
    , t.ArrivedQuantity_LB * 1 AS [Arrived LB], t.ArrivedQuantity_LB * 0.01 AS [Arrived CWT], t.ArrivedQuantity_LB * 0.0005 AS [Arrived TON]
    , t.ArrivedQuantity_PC * 1 AS [Arrived PC]
    , 0 AS [Arrived SQIN]
    , t.AvailablePhysicalQuantity                            AS [Available physical quantity]
    , t.AvailablePhysicalQuantity_FT * 1 AS [Available physical FT], t.AvailablePhysicalQuantity_FT * 12 AS [Available physical IN]
    , t.AvailablePhysicalQuantity_PC * 1 AS [Available physical PC]
    , 0 AS [Available physical SQIN]
    , t.AvailablePhysicalQuantity_LB * 1 AS [Available physical LB], t.AvailablePhysicalQuantity_LB * 0.01 AS [Available physical CWT], t.AvailablePhysicalQuantity_LB * 0.0005 AS [Available physical TON]
    , t.DaysInInventory                                      AS [Days in inventory]
    , t.DeductedQuantity                                     AS [Deducted quantity]
      , t.DeductedQuantity_FT * 1 AS [Deducted FT], t.DeductedQuantity_FT * 12 AS [Deducted IN]
    , t.DeductedQuantity_PC * 1 AS [Deducted PC]
    , 0 AS [Deducted SQIN]
    , t.DeductedQuantity_LB * 1 AS [Deducted LB], t.DeductedQuantity_LB * 0.01 AS [Deducted CWT], t.DeductedQuantity_LB * 0.0005 AS [Deducted TON]
    , t.FinancialCost                                        AS [Financial cost]
    , CAST(1 AS INT)                                         AS [Inventory count]
    , t.MarkedQuantity                                       AS [Marked quantity]
    , t.MarkedQuantity_FT * 1 AS [Marked FT], t.MarkedQuantity_FT * 12 AS [Marked IN]
    , t.MarkedQuantity_PC * 1 AS [Marked PC]
    , 0 AS [Marked SQIN]
    , t.MarkedQuantity_LB * 1 AS [Marked LB], t.MarkedQuantity_LB * 0.01 AS [Marked CWT], t.MarkedQuantity_LB * 0.0005 AS [Marked TON]
    , t.OnHandCost                                           AS [Inventory cost]
    , t.OnHandCost / ISNULL (NULLIF(t.OnHandquantity, 0), 1) AS [Inventory unit cost]
    , t.OnHandquantity                                       AS [Inventory quantity]
    , t.OnHandquantity_FT * 1 AS [Inventory FT], t.OnHandquantity_FT * 12 AS [Inventory IN]
    , t.OnHandquantity_PC * 1 AS [Inventory PC]
    , 0 AS [Inventory SQIN]
    , t.OnHandquantity_LB * 1 AS [Inventory LB], t.OnHandquantity_LB * 0.01 AS [Inventory CWT], t.OnHandquantity_LB * 0.0005 AS [Inventory TON]
    , t.IsClosed                                             AS [Is closed]
    , t.IsClosedQuantity                                     AS [Is closed quantity]
    , t.OnOrderQuantity                                      AS [On-order quantity]
    , t.OnOrderQuantity_FT * 1 AS [On-order FT], t.OnOrderQuantity_FT * 12 AS [On-order IN]
    , t.OnOrderQuantity_PC * 1 AS [On-order PC]
    , 0 AS [On-order SQIN]
    , t.OnOrderQuantity_LB * 1 AS [On-order LB], t.OnOrderQuantity_LB * 0.01 AS [On-order CWT], t.OnOrderQuantity_LB * 0.0005 AS [On-order TON]
    , t.OrderedQuantity                                      AS [Ordered quantity]
    , t.OrderedQuantity_FT * 1 AS [Ordered FT], t.OrderedQuantity_FT * 12 AS [Ordered IN]
    , t.OrderedQuantity_PC * 1 AS [Ordered PC]
    , 0 AS [Ordered SQIN]
    , t.OrderedQuantity_LB * 1 AS [Ordered LB], t.OrderedQuantity_LB * 0.01 AS [Ordered CWT], t.OrderedQuantity_LB * 0.0005 AS [Ordered TON]
    , t.OrderedReservedQuantity                              AS [Ordered reserved quantity]
    , t.OrderedReservedQuantity_FT * 1 AS [Ordered reserved FT], t.OrderedReservedQuantity_FT * 12 AS [Ordered reserved IN]
    , t.OrderedReservedQuantity_PC * 1 AS [Ordered reserved PC]
    , 0 AS [Ordered reserved SQIN]
    , t.OrderedReservedQuantity_LB * 1 AS [Ordered reserved LB], t.OrderedReservedQuantity_LB * 0.01 AS [Ordered reserved CWT], t.OrderedReservedQuantity_LB * 0.0005 AS [Ordered reserved TON]
    , t.PhysicalCost                                         AS [Physical cost]
    , t.PhysicalInventoryQuantity                            AS [Physical inventory quantity]
    , t.PhysicalInventoryQuantity_FT * 1 AS [Physical inventory FT], t.PhysicalInventoryQuantity_FT * 12 AS [Physical inventory IN]
    , t.PhysicalInventoryQuantity_PC * 1 AS [Physical inventory PC]
    , 0 AS [Physical inventory SQIN]
    , t.PhysicalInventoryQuantity_LB * 1 AS [Physical inventory LB], t.PhysicalInventoryQuantity_LB * 0.01 AS [Physical inventory CWT], t.PhysicalInventoryQuantity_LB * 0.0005 AS [Physical inventory TON]
    , t.PhysicalReservedQuantity                             AS [Physical reserved quantity]    
    , t.PhysicalReservedQuantity_FT * 1 AS [Physical reserved FT], t.PhysicalReservedQuantity_FT * 12 AS [Physical reserved IN]
    , t.PhysicalReservedQuantity_PC * 1 AS [Physical reserved PC]
    , 0 AS [Physical reserved SQIN]
    , t.PhysicalReservedQuantity_LB * 1 AS [Physical reserved LB], t.PhysicalReservedQuantity_LB * 0.01 AS [Physical reserved CWT], t.PhysicalReservedQuantity_LB * 0.0005 AS [Physical reserved TON]
    , t.PickedQuantity                                       AS [Picked quantity]
    , t.PickedQuantity_FT * 1 AS [Picked FT], t.PickedQuantity_FT * 12 AS [Picked IN]
    , t.PickedQuantity_PC * 1 AS [Picked PC]
    , 0 AS [Picked SQIN]
    , t.PickedQuantity_LB * 1 AS [Picked LB], t.PickedQuantity_LB * 0.01 AS [Picked CWT], t.PickedQuantity_LB * 0.0005 AS [Picked TON]
    , t.PostedQuantity                                       AS [Posted quantity]
    , t.PostedQuantity_FT * 1 AS [Posted FT], t.PostedQuantity_FT * 12 AS [Posted IN]
    , t.PostedQuantity_PC * 1 AS [Posted PC]
    , 0 AS [Posted SQIN]
    , t.PostedQuantity_LB * 1 AS [Posted LB], t.PostedQuantity_LB * 0.01 AS [Posted CWT], t.PostedQuantity_LB * 0.0005 AS [Posted TON]
    , t.QuoteIssueQuantity                                   AS [Quote issue quantity]
    , t.QuoteIssueQuantity_FT * 1 AS [Quote issue FT], t.QuoteIssueQuantity_FT * 12 AS [Quote issue IN]
    , t.QuoteIssueQuantity_PC * 1 AS [Quote issue PC]
    , 0 AS [Quote issue SQIN]
    , t.QuoteIssueQuantity_LB * 1 AS [Quote issue LB], t.QuoteIssueQuantity_LB * 0.01 AS [Quote issue CWT], t.QuoteIssueQuantity_LB * 0.0005 AS [Quote issue TON]
    , t.QuoteReceiptQuantity                                 AS [Quote receipt quantity]
    , t.QuoteReceiptQuantity_FT * 1 AS [Quote receipt FT], t.QuoteReceiptQuantity_FT * 12 AS [Quote receipt IN]
    , t.QuoteReceiptQuantity_PC * 1 AS [Quote receipt PC]
    , 0 AS [Quote receipt SQIN]
    , t.QuoteReceiptQuantity_LB * 1 AS [Quote receipt LB], t.QuoteReceiptQuantity_LB * 0.01 AS [Quote receipt CWT], t.QuoteReceiptQuantity_LB * 0.0005 AS [Quote receipt TON]
    , t.ReceivedQuantity                                     AS [Received quantity]  
    , t.ReceivedQuantity_FT * 1 AS [Received FT], t.ReceivedQuantity_FT * 12 AS [Received IN]
    , t.ReceivedQuantity_PC * 1 AS [Received PC]
    , 0 AS [Received SQIN]
    , t.ReceivedQuantity_LB * 1 AS [Received LB], t.ReceivedQuantity_LB * 0.01 AS [Received CWT], t.ReceivedQuantity_LB * 0.0005 AS [Received TON]
    , t.RegisteredQuantity                                   AS [Registered quantity]
    , t.RegisteredQuantity_FT * 1 AS [Registered FT], t.RegisteredQuantity_FT * 12 AS [Registered IN]
    , t.RegisteredQuantity_PC * 1 AS [Registered PC]
    , 0 AS [Registered SQIN]
    , t.RegisteredQuantity_LB * 1 AS [Registered LB], t.RegisteredQuantity_LB * 0.01 AS [Registered CWT], t.RegisteredQuantity_LB * 0.0005 AS [Registered TON]
    , t.TotalAvailableQuantity                               AS [Total available quantity]
    , t.TotalAvailableQuantity_FT * 1 AS [Total available FT], t.TotalAvailableQuantity_FT * 12 AS [Total available IN]
    , t.TotalAvailableQuantity_PC * 1 AS [Total available PC]
    , 0 AS [Total available SQIN]
    , t.TotalAvailableQuantity_LB * 1 AS [Total available LB], t.TotalAvailableQuantity_LB * 0.01 AS [Total available CWT], t.TotalAvailableQuantity_LB * 0.0005 AS [Total available TON]
    , NULLIF(t.MasterTagAge, 0)                              AS [Master tag age]
    , NULLIF(t.TagAge, 0)                                    AS [Tag age]
    , NULLIF(t.LastExpectedUpdateDate, '1/1/1900')           AS [Last expected update date]
    , NULLIF(t.LastPhysicalUpdateDate, '1/1/1900')           AS [Last physical update date]
  FROM {{ ref("inventoryonhand_fact") }} t
WHERE IsClosed = 0;
