{{ config(materialized='view', schema='gold', alias="Inventory value trans fact") }}

SELECT  t.InventoryValueTransKey                 AS [Inventory value trans key]
  , t.InventorySiteKey                       AS [Inventory site key]
  , t.InventoryTransKey                      AS [Inventory trans key]
  , t.InventoryTransStatusKey                AS [Inventory trans status key]
  , t.LedgerAccountKey                       AS [Ledger account key]
  , t.LedgerAccountOffsetKey                 AS [Ledger account offset key]
  , t.LegalEntityKey                         AS [Legal entity key]
  , t.LotKey                                 AS [Lot key]
  , t.ProductKey                             AS [Product key]
  , t.TagKey                                 AS [Tag key]
  , t.TransDateKey                           AS [Trans date key]
  , t.VoucherKey                             AS [Voucher key]
  , t.WarehouseKey                           AS [Warehouse key]
  , t.WarehouseLocationKey                   AS [Warehouse location key]
  , t.InventoryAmount                        AS [Inventory value]
  , t.InventoryQuantity                      AS [Inventory quantity]
  , t.InventoryQuantity_LB * 1 AS [Inventory LB], t.InventoryQuantity_LB * 0.01 AS [Inventory CWT], t.InventoryQuantity_LB * 0.0005 AS [Inventory TON]
  , t.InventoryQuantity_PC * 1 AS [Inventory PC]
  , t.InventoryQuantity_FT * 1 AS [Inventory FT], t.InventoryQuantity_FT * 12 AS [Inventory IN]
  , t.InventoryFinancialAmount               AS [Financial value]
  , t.InventoryFinancialQuantity             AS [Financial quantity]      
  , t.InventoryFinancialQuantity_LB * 1 AS [Financial LB], t.InventoryFinancialQuantity_LB * 0.01 AS [Financial CWT], t.InventoryFinancialQuantity_LB * 0.0005 AS [Financial TON]
  , t.InventoryFinancialQuantity_PC * 1 AS [Financial PC]
  , t.InventoryFinancialQuantity_FT * 1 AS [Financial FT], t.InventoryFinancialQuantity_FT * 12 AS [Financial IN]
  , t.InventoryPhysicalNonPostedAmount       AS [Physical non-posted value]
  , t.InventoryPhysicalNonPostedQuantity     AS [Physical non-posted quantity]
  , t.InventoryPhysicalNonPostedQuantity_LB * 1 AS [Physical non-posted LB], t.InventoryPhysicalNonPostedQuantity_LB * 0.01 AS [Physical non-posted CWT], t.InventoryPhysicalNonPostedQuantity_LB * 0.0005 AS [Physical non-posted TON]
  , t.InventoryPhysicalNonPostedQuantity_PC * 1 AS [Physical non-posted PC]
  , t.InventoryPhysicalNonPostedQuantity_FT * 1 AS [Physical non-posted FT], t.InventoryPhysicalNonPostedQuantity_FT * 12 AS [Physical non-posted IN]   
  , t.InventoryPhysicalPostedAmount          AS [Physical posted value]
  , t.InventoryPhysicalPostedQuantity        AS [Physical posted quantity]
  , t.InventoryPhysicalPostedQuantity_LB * 1 AS [Physical posted LB], t.InventoryPhysicalPostedQuantity_LB * 0.01 AS [Physical posted CWT], t.InventoryPhysicalPostedQuantity_LB * 0.0005 AS [Physical posted TON]
  , t.InventoryPhysicalPostedQuantity_PC * 1 AS [Physical posted PC]
  , t.InventoryPhysicalPostedQuantity_FT * 1 AS [Physical posted FT], t.InventoryPhysicalPostedQuantity_FT * 12 AS [Physical posted IN]
  , t.WIPAmount                              AS [WIP value]
  , t.WIPQuantity                            AS [WIP quantity]
  , t.WIPQuantity_LB * 1 AS [WIP posted LB], t.WIPQuantity_LB * 0.01 AS [WIP posted CWT], t.WIPQuantity_LB * 0.0005 AS [WIP posted TON]
  , t.WIPQuantity_PC * 1 AS [WIP posted PC]
  , t.WIPQuantity_FT * 1 AS [WIP posted FT], t.WIPQuantity_FT * 12 AS [WIP posted IN]
FROM {{ ref("InventoryValueTrans_Fact") }} t ;
