{{ config(materialized='view', schema='gold', alias="Packing slip line fact") }}

SELECT  t.PackingSlipLineKey                                                       AS [Packing slip line key]
    , CASE WHEN t.PackingSlipLineKey <> -1 THEN CAST(1 AS SMALLINT)ELSE NULL END AS [Packing slip lines]
    , t.CustomerKey                                                              AS [Customer key]
    , t.DeliveryAddressKey                                                       AS [Delivery address key]
    , t.LegalEntityKey                                                           AS [Legal entity key]
    , t.PackingSlipDateKey                                                       AS [Packing slip date key]
    , t.ProductKey                                                               AS [Product key]
    , t.SalesOrderLineKey                                                        AS [Sales order line key]
    , t.WarehouseKey                                                             AS [Warehouse key]
    , t.OrderedQuantity_SalesUOM                                                 AS [Ordered quantity]
        , t.OrderedQuantity_LB * 1 AS [Ordered LB], t.OrderedQuantity_LB * 0.01 AS [Ordered CWT], t.OrderedQuantity_LB * 0.0005 AS [Ordered TON]
        , t.OrderedQuantity_PC * 1 AS [Ordered PC]
    , t.PriceUnit                                                                AS [Price unit]
    , t.RemainingQuantity_SalesUOM                                               AS [Remaining quantity]
    , t.RemainingQuantity_LB * 1 AS [Remaining LB], t.RemainingQuantity_LB * 0.01 AS [Remaining CWT], t.RemainingQuantity_LB * 0.0005 AS [Remaining TON]
        , t.RemainingQuantity_PC * 1 AS [Remaining PC] 
    , t.ShippedAmount                                                            AS [Shipped amount]
    , t.ShippedQuantity_SalesUOM                                                 AS [Shipped quantity]
    , t.ShippedQuantity_LB * 1 AS [Shipped LB], t.ShippedQuantity_LB * 0.01 AS [Shipped CWT], t.ShippedQuantity_LB * 0.0005 AS [Shipped TON]
        , t.ShippedQuantity_PC * 1 AS [Shipped PC] 
    , NULLIF(t.ShippedNotInvoicedAmount, 0)                                      AS [Ship not invoiced amount]
    , t.ShippedNotInvoicedLineCount                                              AS [Ship not invoiced lines]
    , NULLIF(t.ShippedNotInvoicedQuantity_SalesUOM, 0)                           AS [Ship not invoiced quantity]
    , NULLIF(t.ShippedNotInvoicedQuantity_LB, 0) * 1 AS [Ship not invoiced LB], NULLIF(t.ShippedNotInvoicedQuantity_LB, 0) * 0.01 AS [Ship not invoiced CWT], NULLIF(t.ShippedNotInvoicedQuantity_LB, 0) * 0.0005 AS [Ship not invoiced TON]
        , NULLIF(t.ShippedNotInvoicedQuantity_PC, 0) * 1 AS [Ship not invoiced PC] 
  FROM {{ ref("packingslipline_f") }}     t;
