{{ config(materialized='view', schema='gold', alias="Production pick list journal fact") }}

SELECT  t.ProductionPickListJournalKey AS [Production pick list journal key]
    , t.BOMUOMKey                    AS [BOM UOM key]
    , t.FinancialKey                 AS [Financial key]
    , t.FormulaUOMKey                AS [Formula UOM key]
    , t.LegalEntityKey               AS [Legal entity key]
    , t.ProductionBOMKey             AS [Production BOM key]
    , t.ProductionKey                AS [Production key]
    , t.ProductKey                   AS [Product key]
    , t.TagKey                       AS [Tag key]
    , ISNULL(m.TagKey, -1)           AS [Master tag key]
    , t.MasterProductKey             AS [Master product key]
    , t.TransDateKey                 AS [Trans date key]
    , t.TransDateKey                 AS [Report date key]
    , t.VendorKey                    AS [Vendor key]
    , t.WarehouseKey                 AS [Warehouse key]
    , t.WarehouseLocationKey         AS [Warehouse location key]
    , t.BOMQuantityWithoutYield      AS [BOM quantity without yield]
    , t.BOMQuantityWithoutYield_LB * 1 AS [BOM quantity without yield LB], t.BOMQuantityWithoutYield_LB * 0.01 AS [BOM quantity without yield CWT], t.BOMQuantityWithoutYield_LB * 0.0005 AS [BOM quantity without yield TON]
    , t.BOMQuantityWithoutYield_PC * 1 AS [BOM quantity without yield PC]
    , t.EstimatedMaterialCost        AS [Estimate material cost]
    , t.EstimatedQuantity            AS [Estimate quantity]
    , CAST(t.EstimatedQuantity_LB AS NUMERIC(32,6)) * 1 AS [Estimate LB], CAST(t.EstimatedQuantity_LB AS NUMERIC(32,6)) * 0.01 AS [Estimate CWT], CAST(t.EstimatedQuantity_LB AS NUMERIC(32,6)) * 0.0005 AS [Estimate TON]
    , t.EstimatedQuantity_PC * 1 AS [Estimate PC]
    , t.InventoryCostPerUnit         AS [Inventory cost per unit]
    , t.InventoryCost                AS [Inventory cost]
    , t.IssueQuantity                AS [Issue quantity]
    , CAST(t.IssueQuantity_LB AS numeric(18,4)) * 1 AS [Issue LB], CAST(t.IssueQuantity_LB AS numeric(18,4)) * 0.01 AS [Issue CWT], CAST(t.IssueQuantity_LB AS numeric(18,4)) * 0.0005 AS [Issue TON]
    , t.IssueQuantity_PC * 1 AS [Issue PC]
    , t.MaterialCost                 AS [Material cost]
    , t.PerSeries                    AS [Per series]
    , t.ReleasedQuantity             AS [Released quantity]
    , t.ReleasedQuantity_LB * 1 AS [Released LB], t.ReleasedQuantity_LB * 0.01 AS [Released CWT], t.ReleasedQuantity_LB * 0.0005 AS [Released TON]
    , t.ReleasedQuantity_PC * 1 AS [Released PC]
    , t.RemainQuantity               AS [Remain quantity]    
    , t.RemainQuantity_LB * 1 AS [Remain LB], t.RemainQuantity_LB * 0.01 AS [Remain CWT], t.RemainQuantity_LB * 0.0005 AS [Remain TON]
    , t.RemainQuantity_PC * 1 AS [Remain PC]
    , t.ReturnToStockQuantity        AS [RTS quantity]
    , CAST(t.ReturnToStockQuantity_LB AS numeric(18,4)) * 1 AS [RTS LB], CAST(t.ReturnToStockQuantity_LB AS numeric(18,4)) * 0.01 AS [RTS CWT], CAST(t.ReturnToStockQuantity_LB AS numeric(18,4)) * 0.0005 AS [RTS TON]
    , t.ReturnToStockQuantity_PC * 1 AS [RTS PC]
    , NULLIF(t.JournalID, '')        AS [Journal #]
    , CAST(1 AS INT)                 AS [Production pick list journal count]
  FROM {{ ref("ProductionPickListJournal_Fact") }} t 
INNER JOIN {{ ref("Tag") }}                       tt
    ON tt.TagKey             = t.TagKey
  LEFT JOIN {{ ref("Tag") }}                       m
    ON m.LegalEntityID       = tt.LegalEntityID
  AND m.TagID               = tt.MasterTagID;
