{{ config(materialized='view', schema='gold', alias="Product receipt line fact") }}

SELECT  t.ProductReceiptLineKey                                                       AS [Product receipt line key]
  , t.DeliveryAddressKey                                                          AS [Delivery address key]
  , t.InvoiceVendorKey                                                            AS [Invoice vendor key]
  , t.LegalEntityKey                                                              AS [Legal entity key]
  , t.ProductKey                                                                  AS [Product key]
  , t.PurchaseOrderLineKey                                                        AS [Purchase order line key]
  , t.ReceiptDateKey                                                              AS [Receipt date key]
  , CASE WHEN t.ProductReceiptLineKey <> -1 THEN CAST(1 AS SMALLINT)ELSE NULL END AS [Receipt lines]
  , t.VendorKey                                                                   AS [Vendor key]
  , t.VoucherKey                                                                  AS [Voucher key]
  , t.WarehouseKey                                                                AS [Warehouse key]
  , t.ReceivedAmount                                                              AS [Received amount]
  , t.ReceivedQuantity_PurchUOM                                                   AS [Received quantity]
    , t.ReceivedQuantity_LB * 1 AS [Received LB], t.ReceivedQuantity_LB * 0.01 AS [Received CWT], t.ReceivedQuantity_LB * 0.0005 AS [Received TON]
    , t.ReceivedQuantity_PC * 1 AS [Received PC]
  , t.RemainingQuantity_PurchUOM                                                  AS [Remaining quantity]
  , t.RemainingQuantity_LB * 1 AS [Remaining LB], t.RemainingQuantity_LB * 0.01 AS [Remaining CWT], t.RemainingQuantity_LB * 0.0005 AS [Remaining TON]
    , t.RemainingQuantity_PC * 1 AS [Remaining PC]
  , NULLIF(t.ReceivedNotInvoicedAmount, 0)                                        AS [Receive not invoiced amount]
  , NULLIF(t.ReceivedNotInvoicedDays, 0)                                          AS [Receive not invoiced days]
  , t.ReceivedNotInvoicedlineCount                                                AS [Receive not invoiced lines]
  , NULLIF(t.ReceivedNotInvoicedQuantity_PurchUOM, 0)                             AS [Receive not invoiced quantity]
  , NULLIF(t.ReceivedNotInvoicedQuantity_LB, 0) * 1 AS [Receive not invoiced LB], NULLIF(t.ReceivedNotInvoicedQuantity_LB, 0) * 0.01 AS [Receive not invoiced CWT], NULLIF(t.ReceivedNotInvoicedQuantity_LB, 0) * 0.0005 AS [Receive not invoiced TON]
    , NULLIF(t.ReceivedNotInvoicedQuantity_PC, 0) * 1 AS [Receive not invoiced PC]
  , t.TotalAmount                                                                 AS [Total amount]
FROM {{ ref("productreceiptline_f") }}     t;
