{{ config(materialized='view', schema='gold', alias="Production finished journal fact") }}

SELECT  t.ProductionFinishedJournalKey AS [Production finished journal key]
  , t.FinancialKey                 AS [Financial key]
  , t.InventoryReferenceTypeKey    AS [Inventory reference type key]
  , t.InventorySiteKey             AS [Inventory site key]
  , t.LegalEntityKey               AS [Legal entity key]
  , t.LotKey                       AS [Lot key]
  , t.OrderCreatedDateKey          AS [Order created date key]
  , t.ParentTagKey                 AS [Parent tag key]
  , t.MasterTagKey                 AS [Master tag key]
  , t.MasterProductKey             AS [Master product key]
  , t.PostedDateKey                AS [Posted date key]
  , t.ProductionGroupKey           AS [Production group key]
  , t.ProductionKey                AS [Production key]
  , t.ProductionPoolKey            AS [Production pool key]
  , t.ProductionRemainingStatusKey AS [Production remaining status key]
  , t.ProductionScheduleStatusKey  AS [Production schedule status key]
  , t.ProductionStatusKey          AS [Production status key]
  , t.ProductionTypeKey            AS [Production type key]
  , t.ProductionUOMKey             AS [Production UOM key]
  , t.ProductKey                   AS [Product key]
  , t.ReferenceProductionKey       AS [Reference production key]
  , t.ReportAsFinishedUOMKey       AS [RAF UOM key]
  , t.TagKey                       AS [Tag key]
  , t.TransDateKey                 AS [Trans date key]
  , t.WarehouseKey                 AS [Warehouse key]
  , t.WarehouseLocationKey         AS [Warehouse location key]
  , t.ActualRunQuantity            AS [Produced quantity]
  ,CAST(t.ActualRunQuantity_LB AS NUMERIC(18,4)) * 1 AS [Produced LB], CAST(t.ActualRunQuantity_LB AS NUMERIC(18,4)) * 0.01 AS [Produced CWT], CAST(t.ActualRunQuantity_LB AS NUMERIC(18,4)) * 0.0005 AS [Produced TON]
  ,CAST(t.ActualRunQuantity_PC AS NUMERIC(18,4)) * 1 AS [Produced PC]
  , NULLIF(t.JournalID, '')        AS [Journal #]
  , t.PostedTime                   AS [Posted time]
  , CAST(1 AS INT)                 AS [Production finished journal count]
FROM {{ ref("productionfinishedjournal_f") }} t;
