{{ config(materialized='view', schema='gold', alias="Project") }}

SELECT  t.ProjectKey                    AS [Project key]
  , NULLIF(t.ProjectID, '')         AS [Project ID]
  , NULLIF(t.ParentProjectID, '')   AS [Parent project ID]
  , NULLIF(t.ProjectGroup, '')      AS [Project group]
  , NULLIF(t.ProjectName, '')       AS [Project name]
  , t.ProjectStateID                AS [Project state ID]
  , NULLIF(t.ProjectState, '')      AS [Project state]
  , NULLIF(t.ProjectIDLevel1, '')   AS [Project level 1 ID]
  , NULLIF(t.ProjectIDLevel2, '')   AS [Project level 2 ID]
  , NULLIF(t.ProjectIDLevel3, '')   AS [Project level 3 ID]
  , NULLIF(t.ProjectIDLevel4, '')   AS [Project level 4 ID]
  , NULLIF(t.ProjectIDLevel5, '')   AS [Project level 5 ID]
  , NULLIF(t.ProjectIDLevel6, '')   AS [Project level 6 ID]
  , NULLIF(t.ProjectIDLevel7, '')   AS [Project level 7 ID]
  , NULLIF(t.ProjectIDLevel8, '')   AS [Project level 8 ID]
  , NULLIF(t.ProjectNameLevel1, '') AS [Project level 1]
  , NULLIF(t.ProjectNameLevel2, '') AS [Project level 2]
  , NULLIF(t.ProjectNameLevel3, '') AS [Project level 3]
  , NULLIF(t.ProjectNameLevel4, '') AS [Project level 4]
  , NULLIF(t.ProjectNameLevel5, '') AS [Project level 5]
  , NULLIF(t.ProjectNameLevel6, '') AS [Project level 6]
  , NULLIF(t.ProjectNameLevel7, '') AS [Project level 7]
  , NULLIF(t.ProjectNameLevel8, '') AS [Project level 8]
FROM {{ ref("Project") }} t;
