{{ config(materialized='view', schema='gold', alias="Purchase invoice trans fact") }}

WITH Charges
AS (
  SELECT  pilcf.PurchaseInvoiceLineTransKey
        , SUM(CASE WHEN cc.ChargeCode = 'Mill Pkg' THEN pilcf.TotalCharges ELSE 0 END)            AS [Mill packaging extra]
        , SUM(CASE WHEN cc.ChargeCode = 'Mill Pkg' THEN pilcf.TotalCharges_TransCur ELSE 0 END)   AS [Mill packaging extra in trans currency]
        , SUM(CASE WHEN cc.ChargeCode = 'Fuel Surch' THEN pilcf.TotalCharges ELSE 0 END)          AS [Fuel surcharge]
        , SUM(CASE WHEN cc.ChargeCode = 'Fuel Surch' THEN pilcf.TotalCharges_TransCur ELSE 0 END) AS [Fuel surcharge in trans currency]
        , SUM(CASE WHEN cc.ChargeCode = 'Freight' THEN pilcf.TotalCharges ELSE 0 END)             AS [Freight prepaid]
        , SUM(CASE WHEN cc.ChargeCode = 'Freight' THEN pilcf.TotalCharges_TransCur ELSE 0 END)    AS [Freight prepaid in trans currency]
        , SUM(CASE WHEN cc.ChargeCode = 'OSP_INV' THEN pilcf.TotalCharges ELSE 0 END)             AS [OSP consignment inventory invoice]
        , SUM(CASE WHEN cc.ChargeCode = 'OSP_INV' THEN pilcf.TotalCharges_TransCur ELSE 0 END)    AS [OSP consignment inventory invoice in trans currency]
    FROM {{ ref("PurchaseInvoiceLineChargeTrans_Fact") }} pilcf  
    LEFT JOIN {{ ref("PurchaseInvoiceLineCharge_Fact") }} pilc  
      ON pilc.PurchaseInvoiceLineChargeKey = pilcf.PurchaseInvoiceLineChargeKey
    LEFT JOIN {{ ref("ChargeCode") }}                     cc
      ON cc.ChargeCodeKey                  = pilc.ChargeCodeKey
    GROUP BY pilcf.PurchaseInvoiceLineTransKey)
SELECT  piltf.PurchaseInvoiceLineTransKey               AS [Purchase invoice line trans key]
  , COALESCE(pilf.InvoiceDateKey, -1)               AS [Invoice date key]
  , CAST(1 AS INT)                                  AS [Invoice trans count]
  , piltf.BaseAmount                                AS [Invoice base amount]
  , piltf.BaseAmount_TransCur                       AS [Invoice base amount in trans currency]
  , piltf.NetAmount                                 AS [Invoice net amount]
  , piltf.NetAmount_TransCur                        AS [Invoice net amount in trans currency]
  , ISNULL(piltf.BaseUnitPrice, 0)                  AS [Invoice base unit price]
  , ISNULL(piltf.BaseUnitPrice_TransCur, 0)         AS [Invoice base unit price in trans currency]
  , ISNULL(piltf.DiscountAmount, 0)                 AS [Invoice discount]
  , ISNULL(piltf.DiscountAmount_TransCur, 0)        AS [Invoice discount in trans currency]
  , ISNULL(piltf.InvoiceTotalAmount, 0)             AS [Invoice total]
  , ISNULL(piltf.InvoiceTotalAmount_TransCur, 0)    AS [Invoice total in trans currency]
  , ISNULL(piltf.InvoiceQuantity_PurchUOM, 0)       AS [Invoice quantity]
    , ISNULL(piltf.InvoiceQuantity_LB, 0) * 1 AS [Invoice LB], ISNULL(piltf.InvoiceQuantity_LB, 0) * 0.01 AS [Invoice CWT], ISNULL(piltf.InvoiceQuantity_LB, 0) * 0.0005 AS [Invoice TON]
    , ISNULL(piltf.InvoiceQuantity_PC, 0) * 1 AS [Invoice PC]
    , ISNULL(piltf.PriceUnit, 0)                      AS [Invoice price unit]
  , ISNULL(piltf.TaxAmount, 0)                      AS [Invoice tax]
  , ISNULL(piltf.TaxAmount_TransCur, 0)             AS [Invoice tax in trans currency]
  , ISNULL(piltf.InvoicePurchaseAmount, 0)          AS [Invoice purchase amount]
  , ISNULL(piltf.InvoicePurchaseAmount_TransCur, 0) AS [Invoice purchase amount in trans currency]
  , ISNULL(piltf.TotalUnitPrice, 0)                 AS [Invoice total unit price]
  , ISNULL(piltf.TotalUnitPrice_TransCur, 0)        AS [Invoice total unit price in trans currency]
  , ISNULL(piltf.AdditionalCharge, 0)               AS [Invoice additional charges]
  , ISNULL(piltf.AdditionalCharge_TransCur, 0)      AS [Invoice additional charges in trans currency]
  , ISNULL(piltf.IncludedCharge, 0)                 AS [Invoice included charges]
  , ISNULL(piltf.IncludedCharge_TransCur, 0)        AS [Invoice included charges in trans currency]
  , ISNULL(piltf.VendorCharge, 0)                   AS [Invoice total charges]
  , ISNULL(piltf.VendorCharge_TransCur, 0)          AS [Invoice total charges in trans currency]
  , ISNULL(piltf.NonBillableCharge, 0)              AS [Invoice non-billable charges]
  , ISNULL(piltf.NonBillableCharge_TransCur, 0)     AS [Invoice non-billable charges in trans currency]
  , [Mill packaging extra]
  , [Mill packaging extra in trans currency]
  , [Fuel surcharge]
  , [Fuel surcharge in trans currency]
  , [Freight prepaid]
  , [Freight prepaid in trans currency]
  , [OSP consignment inventory invoice]
  , [OSP consignment inventory invoice in trans currency]
FROM {{ ref("PurchaseInvoiceLineTrans_Fact") }} piltf  
INNER JOIN {{ ref("PurchaseInvoiceLine_Fact") }} pilf  
  ON pilf.PurchaseInvoiceLineKey       = piltf.PurchaseInvoiceLineKey
LEFT JOIN Charges                      pilcf  
  ON pilcf.PurchaseInvoiceLineTransKey = piltf.PurchaseInvoiceLineTransKey
UNION ALL
SELECT  -1             AS [Purchase invoice line trans key]
  , -1             AS [Invoice date key]
  , CAST(0 AS INT) AS [Invoice trans count]
  , NULL              AS [Invoice base amount]
  , NULL              AS [Invoice base amount in trans currency]
  , NULL              AS [Invoice net amount]
  , NULL              AS [Invoice net amount in trans currency]
  , NULL              AS [Invoice base unit price]
  , NULL              AS [Invoice base unit price in trans currency]
  , NULL              AS [Invoice discount]
  , NULL              AS [Invoice discount in trans currency]
  , NULL              AS [Invoice total]
  , NULL              AS [Invoice total in trans currency]
  , NULL              AS [Invoice quantity]
    , 0 AS [Invoice LB], 0 AS [Invoice CWT], 0 AS [Invoice TON]
    , 0 AS [Invoice PC]
  , NULL              AS [Invoice price unit]
  , NULL              AS [Invoice tax]
  , NULL              AS [Invoice tax in trans currency]
  , NULL              AS [Invoice purchase amount]
  , NULL              AS [Invoice purchase amount in trans currency]
  , NULL              AS [Invoice total unit price]
  , NULL              AS [Invoice total unit price in trans currency]
  , NULL              AS [Invoice additional charges]
  , NULL              AS [Invoice additional charges in trans currency]
  , NULL              AS [Invoice included charges]
  , NULL              AS [Invoice included charges in trans currency]
  , NULL              AS [Invoice total charges]
  , NULL              AS [Invoice total charges in trans currency]
  , NULL              AS [Invoice non-billable charges]
  , NULL              AS [Invoice non-billable charges in trans currency]
  , NULL              AS [Mill packaging extra]
  , NULL              AS [Mill packaging extra in trans currency]
  , NULL              AS [Fuel surcharge]
  , NULL              AS [Fuel surcharge in trans currency]
  , NULL              AS [Freight prepaid]
  , NULL              AS [Freight prepaid in trans currency]
  , NULL              AS [OSP consignment inventory invoice]
  , NULL              AS [OSP consignment inventory invoice in trans currency];
