{{ config(materialized='view', schema='gold', alias="Purchase requisition line fact") }}

SELECT  t.PurchaseRequisitionLineKey AS [Purchase requisition line key]
    , t.BuyerGroupKey              AS [Buyer group key]
    , t.CreatedDateKey             AS [Created date key]
    , t.CurrencyKey                AS [Currency key]
    , t.DocumentStateKey           AS [Document state key]
    , t.LegalEntityKey             AS [Legal entity key]
    , t.ProductKey                 AS [Product key]
    , t.ProcurementCategoryKey     AS [Procurement category key]
    , t.PurchaseOrderLineKey       AS [Purchase order line key]
    , t.PurchaseUOMKey             AS [Purchase UOM key]
    , t.RequiredDateKey            AS [Required date key]
    , t.InventorySiteKey           AS [Inventory site key]
    , t.VendorKey                  AS [Vendor key]
    , t.NetAmount                  AS [Requisition amount]
    , t.NetAmount_TransCur         AS [Requisition amount in trans currency]
    , t.ChargeAmount               AS [Requisition charges]
    , t.ChargeAmount_TransCur      AS [Requisition charges in trans currency]
    , t.DiscountAmount             AS [Requisition discount]
    , t.DiscountAmount_TransCur    AS [Requisition discount in trans currency]
    , t.RequisitionQuantity        AS [Requisition quantity]
      ,t.RequisitionQuantity_LB * 1 AS [Requisition LB], t.RequisitionQuantity_LB * 0.01 AS [Requisition CWT], t.RequisitionQuantity_LB * 0.0005 AS [Requisition TON]
      ,t.RequisitionQuantity_PC * 1 AS [Requisition PC]
      ,t.RequisitionQuantity_FT * 1 AS [Requisition FT], t.RequisitionQuantity_FT * 12 AS [Requisition IN]
      ,t.RequisitionQuantity_SQIN * 1 AS [Requisition SQIN]
    , t.PriceUnit                  AS [Requisition price unit]
    , t.BasePrice                  AS [Requisition price]
    , t.BasePrice_TransCur         AS [Requisition price in trans currency]
    , CAST(1 AS INT)               AS [Requisition lines]
    , d.Date                       AS [Created date]
  FROM {{ ref("purchaserequisitionline_f") }}     t
INNER JOIN {{ ref("Date") }}                        d 
    ON d.DateKey                          = t.CreatedDateKey;
