{{ config(materialized='view', schema='gold', alias="Purchase order trans fact") }}

SELECT  poltf.PurchaseOrderLineTransKey                 AS [Purchase order line trans key]
    , CAST(1 AS INT)                                        AS [Order trans count]
    , COALESCE(polf.OrderDateKey, 19000101)                 AS [Order date key]
    , poltf.BaseAmount                                      AS [Order base amount]
    , poltf.BaseAmount_TransCur                             AS [Order base amount in trans currency]
    , poltf.NetAmount                                       AS [Order net amount]
    , poltf.NetAmount_TransCur                              AS [Order net amount in trans currency]
    , ISNULL(poltf.BaseUnitPrice, 0)                        AS [Order base unit price]
    , ISNULL(poltf.BaseUnitPrice_TransCur, 0)               AS [Order base unit price in trans currency]
    , ISNULL(poltf.DiscountAmount, 0)                       AS [Order discount]
    , ISNULL(poltf.DiscountAmount_TransCur, 0)              AS [Order discount in trans currency]
    , ISNULL(poltf.AdditionalCharge, 0)                     AS [Order additional charges]
    , ISNULL(poltf.AdditionalCharge_TransCur, 0)            AS [Order additional charges in trans currency]
    , ISNULL(poltf.NonBillableCharge, 0)                    AS [Order non-billable charges]
    , ISNULL(poltf.NonBillableCharge_TransCur, 0)           AS [Order non-billable charges in trans currency]
    , ISNULL(poltf.IncludedCharge, 0)                       AS [Order included charges]
    , ISNULL(poltf.IncludedCharge_TransCur, 0)              AS [Order included charges in trans currency]
    , ISNULL(poltf.OrderedPurchaseAmount, 0)                AS [Order purchase amount]
    , ISNULL(poltf.OrderedPurchaseAmount_TransCur, 0)       AS [Order purchase amount in trans currency]
    , ISNULL(poltf.TotalUnitPrice, 0)                       AS [Order total unit price]
    , ISNULL(poltf.TotalUnitPrice_TransCur, 0)              AS [Order total unit price in trans currency]
    , ISNULL(poltf.VendorCharge, 0)                         AS [Order total charges]
    , ISNULL(poltf.VendorCharge_TransCur, 0)                AS [Order total charges in trans currency]
    , ISNULL(poltf.OrderedQuantity_PurchUOM, 0)             AS [Order trans quantity]
      , ISNULL(poltf.OrderedQuantity_LB, 0) * 1 AS [Order trans LB], ISNULL(poltf.OrderedQuantity_LB, 0) * 0.01 AS [Order trans CWT], ISNULL(poltf.OrderedQuantity_LB, 0) * 0.0005 AS [Order trans TON]
      , ISNULL(poltf.OrderedQuantity_PC, 0) * 1 AS [Order trans PC]
    , ISNULL(poltf.PhysicalCost, 0)                         AS [Physical cost]
    , ISNULL(poltf.PriceUnit, 0)                            AS [Order price unit]
    , ISNULL(poltf.RemainingAmount, 0)                      AS [Receive remain amount]
    , ISNULL(poltf.RemainingAmount_TransCur, 0)             AS [Receive remain amount in trans currency]
    , NULLIF(poltf.RemainingQuantity_PurchUOM, 0)           AS [Receive remain quantity]
    , NULLIF(poltf.RemainingQuantity_LB, 0) * 1 AS [Receive remain LB], NULLIF(poltf.RemainingQuantity_LB, 0) * 0.01 AS [Receive remain CWT], NULLIF(poltf.RemainingQuantity_LB, 0) * 0.0005 AS [Receive remain TON]
    , NULLIF(poltf.RemainingQuantity_PC, 0) * 1 AS [Receive remain PC]
  FROM {{ ref("PurchaseOrderLineTrans_Fact") }} poltf 
INNER JOIN {{ ref("PurchaseOrderLine_Fact") }} polf 
    ON polf.PurchaseOrderLineKey = poltf.PurchaseOrderLineKey
UNION ALL
SELECT  -1       AS [Purchase order line trans key]
    , 0        AS [Order trans count]
    , 19000101 AS [Order date key]
    , NULL        AS [Order base amount]
    , NULL        AS [Order base amount in trans currency]
    , NULL        AS [Order net amount]
    , NULL        AS [Order net amount in trans currency]
    , NULL        AS [Order base unit price]
    , NULL        AS [Order base unit price in trans currency]
    , NULL        AS [Order discount]
    , NULL        AS [Order discount in trans currency]
    , NULL        AS [Order additional charges]
    , NULL        AS [Order additional charges in trans currency]
    , NULL        AS [Order non-billable charges]
    , NULL        AS [Order non-billable charges in trans currency]
    , NULL        AS [Order included charges]
    , NULL        AS [Order included charges in trans currency]
    , NULL        AS [Order purchase amount]
    , NULL        AS [Order purchase amount in trans currency]
    , NULL        AS [Order total unit price]
    , NULL        AS [Order total unit price in trans currency]
    , NULL        AS [Order total charges]
    , NULL        AS [Order total charges in trans currency]
    , NULL        AS [Order trans quantity]
      , 0 AS [Order trans LB], 0 AS [Order trans CWT], 0 AS [Order trans TON]
      , 0 AS [Order trans PC]
    , NULL        AS [Physical cost]
    , NULL        AS [Order price unit]
    , NULL        AS [Receive remain amount]
    , NULL        AS [Receive remain amount in trans currency]
    , NULL     AS [Receive remain quantity]
    , 0 AS [Receive remain LB], 0 AS [Receive remain CWT], 0 AS [Receive remain TON]
    , 0 AS [Receive remain PC];
