{{ config(materialized='view', schema='gold', alias="Sales order trans fact") }}

SELECT  soltf.SalesOrderLineTransKey                          AS [Sales order line trans key]
    , COALESCE(solf.OrderDateKey, -1)                       AS [Created date key]
    , CAST(1 AS INT)                                        AS [Sales order trans count]
    , soltf.BaseAmount                                      AS [Order base amount]
    , soltf.BaseAmount_TransCur                             AS [Order base amount in trans currency]
    , NULLIF(soltf.DaysReserved, 0)                         AS [Days reserved]
    , soltf.NetAmount                                       AS [Order net amount]
    , soltf.NetAmount_TransCur                              AS [Order net amount in trans currency]
    , soltf.BaseUnitPrice                                   AS [Order base unit price]
    , soltf.BaseUnitPrice_TransCur                          AS [Order base unit price in trans currency]
    , soltf.AdditionalCharge                                AS [Order additional charges]
    , soltf.AdditionalCharge_TransCur                       AS [Order additional charges in trans currency]
    , soltf.IncludedCharge                                  AS [Order included charges]
    , soltf.IncludedCharge_TransCur                         AS [Order included charges in trans currency]
    , soltf.NonBillableCharge                               AS [Order non-billable charges]
    , soltf.NonBillableCharge_TransCur                      AS [Order non-billable charges in trans currency]
    , soltf.CustomerCharge                                  AS [Order total charges]
    , soltf.CustomerCharge_TransCur                         AS [Order total charges in trans currency]
    , soltf.DiscountAmount                                  AS [Order discount]
    , soltf.DiscountAmount_TransCur                         AS [Order discount in trans currency]
    , soltf.OrderedSalesAmount                              AS [Order sales amount]
    , soltf.OrderedSalesAmount_TransCur                     AS [Order sales amount in trans currency]
    , soltf.TotalUnitPrice                                  AS [Order total unit price]
    , soltf.TotalUnitPrice_TransCur                         AS [Order total unit price in trans currency]
    , soltf.OrderedQuantity_SalesUOM                        AS [Order trans quantity]
      , soltf.OrderedQuantity_LB * 1 AS [Order trans LB], soltf.OrderedQuantity_LB * 0.01 AS [Order trans CWT], soltf.OrderedQuantity_LB * 0.0005 AS [Order trans TON]
      , soltf.OrderedQuantity_PC * 1 AS [Order trans PC]
    , soltf.PhysicalCost                                    AS [Physical cost]
    , soltf.PriceUnit                                       AS [Order price unit]
    , soltf.RemainingAmount                                 AS [Ship remain amount]
    , soltf.RemainingAmount_TransCur                        AS [Ship remain amount in trans currency]
    , NULLIF(soltf.RemainingQuantity_SalesUOM, 0)           AS [Ship remain quantity]
    , NULLIF(soltf.RemainingQuantity_LB, 0) * 1 AS [Ship remain LB], NULLIF(soltf.RemainingQuantity_LB, 0) * 0.01 AS [Ship remain CWT], NULLIF(soltf.RemainingQuantity_LB, 0) * 0.0005 AS [Ship remain TON]
      , NULLIF(soltf.RemainingQuantity_PC, 0) * 1 AS [Ship remain PC]
    , NULLIF(soltf.PhysicalReservedQuantity_SalesUOM, 0)    AS [Physical reserved quantity]
    , NULLIF(soltf.PhysicalReservedQuantity_LB, 0) * 1 AS [Physical reserved LB], NULLIF(soltf.PhysicalReservedQuantity_LB, 0) * 0.01 AS [Physical reserved CWT], NULLIF(soltf.PhysicalReservedQuantity_LB, 0) * 0.0005 AS [Physical reserved TON]
      , NULLIF(soltf.PhysicalReservedQuantity_PC, 0) * 1 AS [Physical reserved PC]
    , CAST(NULLIF(soltf.AvailableDate, '1/1/1900') AS DATE) AS [Available date]
    , CAST(NULLIF(soltf.ReserveDate, '1/1/1900') AS DATE)   AS [Reserve date]
  FROM {{ ref("salesorderlinetrans_fact") }} soltf 
  LEFT JOIN {{ ref("salesorderline_fact") }} solf 
    ON solf.SalesOrderLineKey     = soltf.SalesOrderLineKey
WHERE soltf._SourceID = 1
UNION ALL
SELECT  -1   AS [Sales order line trans key]
    , -1   AS [Created date key]
    , 0    AS [Sales order trans count]
    , NULL    AS [Order base amount]
    , NULL    AS [Order base amount in trans currency]
    , NULL    AS [Days reserved]
    , NULL    AS [Order net amount]
    , NULL    AS [Order net amount in trans currency]
    , NULL    AS [Order base unit price]
    , NULL    AS [Order base unit price in trans currency]
    , NULL    AS [Order additional charges]
    , NULL    AS [Order additional charges in trans currency]
    , NULL    AS [Order included charges]
    , NULL    AS [Order included charges in trans currency]
    , NULL    AS [Order non-billable charges]
    , NULL    AS [Order non-billable charges in trans currency]
    , NULL    AS [Order total charges]
    , NULL    AS [Order total charges in trans currency]
    , NULL    AS [Order discount]
    , NULL    AS [Order discount in trans currency]
    , NULL    AS [Order sales amount]
    , NULL    AS [Order sales amount in trans currency]
    , NULL    AS [Order total unit price]
    , NULL    AS [Order total unit price in trans currency]
    , NULL    AS [Order trans quantity]
    , 0 AS [Order trans LB], 0 AS [Order trans CWT], 0 AS [Order trans TON]
    , 0 AS [Order trans PC]
    , NULL    AS [Physical cost]
    , NULL    AS [Order price unit]
    , NULL    AS [Ship remain amount]
    , NULL    AS [Ship remain amount in trans currency]
    , NULL AS [Ship remain quantity]
    , 0 AS [Ship remain LB], 0 AS [Ship remain CWT], 0 AS [Ship remain TON]
      , 0 AS [Ship remain PC]
    , NULL AS [Physical reserved quantity]
    , 0 AS [Physical reserved LB], 0 AS [Physical reserved CWT], 0 AS [Physical reserved TON]
      , 0 AS [Physical reserved PC]
    , NULL AS [Available date]
    , NULL AS [Reserve date];
