{{ config(materialized='view', schema='gold', alias="Sales quote line fact") }}

SELECT  t.SalesQuoteLineKey             AS [Sales quote line key]
    , t.CurrencyKey                   AS [Currency key]
    , t.CustomerKey                   AS [Customer key]
    , t.ExpirationDateKey             AS [Expiration date key]
    , t.FinancialKey                  AS [Financial key]
    , t.InventorySiteKey              AS [Inventory site key]
    , t.InvoiceCustomerKey            AS [Invoice customer key]
    , t.LegalEntityKey                AS [Legal entity key]
    , t.LotKey                        AS [Lot key]
    , t.ProductKey                    AS [Product key]
    , t.QuoteDateKey                  AS [Quote date key]
    , t.ReceiptDateRequestedKey       AS [Receipt date requested key]
    , t.SalesCategoryKey              AS [Sales category key]
    , t.ShipDateRequestedKey          AS [Ship date requested key]
    , t.WarehouseKey                  AS [Warehouse key]
    , t.BaseUnitPrice                 AS [Quote base unit price]
    , t.BaseUnitPrice_TransCur        AS [Quote base unit price in trans currency]
    , t.DiscountAmount                AS [Quote discount]
    , t.DiscountAmount_TransCur       AS [Quote discount in trans currency]
    , t.NetAmount                     AS [Quote net amount]
    , t.NetAmount_TransCur            AS [Quote net amount in trans currency]
    , t.OrderedQuantity_SalesUOM      AS [Quote quantity]
      , t.OrderedQuantity_LB * 1 AS [Quote LB], t.OrderedQuantity_LB * 0.01 AS [Quote CWT], t.OrderedQuantity_LB * 0.0005 AS [Quote TON]
      , t.OrderedQuantity_PC * 1 AS [Quote PC]
    , t.PriceUnit                     AS [Quote price unit]
    , CAST(1 AS INT)                  AS [Quote lines]
    , t.RemainingQuantity_SalesUOM    AS [Quote remain quantity]
    , t.RemainingQuantity_LB * 1 AS [Quote remain LB], t.RemainingQuantity_LB * 0.01 AS [Quote remain CWT], t.RemainingQuantity_LB * 0.0005 AS [Quote remain TON]
      , t.RemainingQuantity_PC * 1 AS [Quote remain PC]
    , t.TotalAmount                   AS [Quote amount]
    , t.TotalAmount_TransCur          AS [Quote amount in trans currency]
    , t.TotalUnitPrice                AS [Quote unit price]
    , t.TotalUnitPrice_TransCur       AS [Quote unit price in trans currency]
    , NULLIF(t.CustomerReference, '') AS [Customer reference]
  FROM {{ ref("salesquoteline_fact") }}     t;
