{{ config(materialized='view', schema='gold', alias="Sales invoice trans fact") }}

WITH Charges
  AS (
    SELECT  silcf.SalesInvoiceLineTransKey
          , SUM(CASE WHEN cc.ChargeCode = 'Gross Wght' THEN silcf.TotalCharges END)          AS [Gross weight charges]
          , SUM(CASE WHEN cc.ChargeCode = 'Gross Wght' THEN silcf.TotalCharges_TransCur END) AS [Gross weight charges in trans currency]
          , SUM(CASE WHEN cc.ChargeCode = 'WEIGHTS' THEN silcf.TotalCharges END)             AS [Weights charges]
          , SUM(CASE WHEN cc.ChargeCode = 'WEIGHTS' THEN silcf.TotalCharges_TransCur END)    AS [Weights charges in trans currency]
          , SUM(CASE WHEN cc.ChargeCode = 'SALES_FRT' THEN silcf.TotalCharges END)           AS [Sales freight charges]
          , SUM(CASE WHEN cc.ChargeCode = 'SALES_FRT' THEN silcf.TotalCharges_TransCur END)  AS [Sales freight charges in trans currency]
          , SUM(CASE WHEN cc.ChargeCode = 'BundBreak' THEN silcf.TotalCharges END)           AS [Bundle break fee]
          , SUM(CASE WHEN cc.ChargeCode = 'BundBreak' THEN silcf.TotalCharges_TransCur END)  AS [Bundle break fee in trans currency]
      FROM {{ ref("salesinvoicelinechargetrans_f") }} silcf
      LEFT JOIN {{ ref("salesinvoicelinecharge_f") }} solc 
        ON solc.SalesInvoiceLineChargeKey = silcf.SalesInvoiceLineChargeKey
      LEFT JOIN {{ ref("chargecode_d") }}                  cc 
        ON cc.ChargeCodeKey               = solc.ChargeCodeKey
      GROUP BY silcf.SalesInvoiceLineTransKey)
SELECT  siltf.SalesInvoiceLineTransKey                                                   AS [Sales invoice line trans key]
    , COALESCE(silf.InvoiceDateKey, 19000101)                                          AS [Invoice date key]
    , CAST(1 AS INT)                                                                   AS [Invoice trans count]
    , siltf.BaseAmount                                                                 AS [Invoice base amount]
    , siltf.BaseAmount_TransCur                                                        AS [Invoice base amount in trans currency]
    , siltf.NetAmount                                                                  AS [Invoice net amount]
    , siltf.NetAmount_TransCur                                                         AS [Invoice net amount in trans currency]
    , siltf.CustomerCharge                                                             AS [Invoice total charges]
    , siltf.CustomerCharge_TransCur                                                    AS [Invoice total charges in trans currency]
    , siltf.BaseUnitPrice                                                              AS [Invoice base unit price]
    , siltf.BaseUnitPrice_TransCur                                                     AS [Invoice base unit price in trans currency]
    , siltf.CostAmount                                                                 AS [Invoice sales cost]
    , siltf.CostAmount_TransCur                                                        AS [Invoice sales cost in trans currency]
    , siltf.CostAmount / ISNULL(NULLIF(siltf.InvoiceQuantity_SalesUOM, 0), 1)          AS [Invoice cost unit price]
    , siltf.CostAmount_TransCur / ISNULL(NULLIF(siltf.InvoiceQuantity_SalesUOM, 0), 1) AS [Invoice cost unit price in trans currency]
    , siltf.GrossProfit                                                                AS [Invoice GP]
    , siltf.GrossProfit_TransCur                                                       AS [Invoice GP in trans currency]
    , siltf.DiscountAmount                                                             AS [Invoice discount]
    , siltf.DiscountAmount_TransCur                                                    AS [Invoice discount in trans currency]
    , siltf.InvoiceTotalAmount                                                         AS [Invoice total]
    , siltf.InvoiceTotalAmount_TransCur                                                AS [Invoice total in trans currency]
    , siltf.InvoiceQuantity_SalesUOM                                                   AS [Invoice quantity]
    , siltf.InvoiceQuantity_LB * 1 AS [Invoice LB], siltf.InvoiceQuantity_LB * 0.01 AS [Invoice CWT], siltf.InvoiceQuantity_LB * 0.0005 AS [Invoice TON]
    , siltf.InvoiceQuantity_PC * 1 AS [Invoice PC]
    , siltf.PriceUnit                                                                  AS [Invoice price unit]
    , siltf.TaxAmount                                                                  AS [Invoice tax]
    , siltf.TaxAmount_TransCur                                                         AS [Invoice tax in trans currency]
    , siltf.InvoiceSalesAmount                                                         AS [Invoice sales amount]
    , siltf.InvoiceSalesAmount_TransCur                                                AS [Invoice sales amount in trans currency]
    , siltf.TotalUnitPrice                                                             AS [Invoice total unit price]
    , siltf.TotalUnitPrice_TransCur                                                    AS [Invoice total unit price in trans currency]
    , siltf.AdditionalCharge                                                           AS [Invoice additional charges]
    , siltf.AdditionalCharge_TransCur                                                  AS [Invoice additional charges in trans currency]
    , siltf.IncludedCharge                                                             AS [Invoice included charges]
    , siltf.IncludedCharge_TransCur                                                    AS [Invoice included charges in trans currency]
    , siltf.NonBillableCharge                                                          AS [Invoice non-billable charges]
    , siltf.NonBillableCharge_TransCur                                                 AS [Invoice non-billable charges in trans currency]
    , [Gross weight charges]                                                           AS [Gross weight charges]
    , [Gross weight charges in trans currency]                                         AS [Gross weight charges in trans currency]
    , [Weights charges]                                                                AS [Weights charges]
    , [Weights charges in trans currency]                                              AS [Weights charges in trans currency]
    , [Sales freight charges]                                                          AS [Sales freight charges]
    , [Sales freight charges in trans currency]                                        AS [Sales freight charges in trans currency]
    , [Bundle break fee]                                                               AS [Bundle break fee]
    , [Bundle break fee in trans currency]                                             AS [Bundle break fee in trans currency]
  FROM {{ ref("salesinvoicelinetrans_f") }} siltf 
  LEFT JOIN {{ ref("salesinvoiceline_f") }} silf 
    ON silf.SalesInvoiceLineKey       = siltf.SalesInvoiceLineKey
  LEFT JOIN {{ ref("salesinvoice_d") }}          si 
    ON si.SalesInvoiceKey             = silf.SalesInvoiceKey
  LEFT JOIN Charges                   silcf
    ON silcf.SalesInvoiceLineTransKey = siltf.SalesInvoiceLineTransKey
WHERE siltf._SourceID = 1 
UNION ALL
SELECT  -1             AS [Sales invoice line trans key]
    , 19000101       AS [Invoice date key]
    , CAST(0 AS INT) AS [Invoice trans count]
    , NULL              AS [Invoice base amount]
    , NULL              AS [Invoice base amount in trans currency]
    , NULL              AS [Invoice net amount]
    , NULL              AS [Invoice net amount in trans currency]
    , NULL              AS [Invoice total charges]
    , NULL              AS [Invoice total charges in trans currency]
    , NULL              AS [Invoice base unit price]
    , NULL              AS [Invoice base unit price in trans currency]
    , NULL              AS [Invoice sales cost]
    , NULL              AS [Invoice sales cost in trans currency]
    , NULL              AS [Invoice cost unit price]
    , NULL              AS [Invoice cost unit price in trans currency]
    , NULL              AS [Invoice GP]
    , NULL              AS [Invoice GP in trans currency]
    , NULL              AS [Invoice discount]
    , NULL              AS [Invoice discount in trans currency]
    , NULL              AS [Invoice total]
    , NULL              AS [Invoice total in trans currency]
    , NULL              AS [Invoice quantity]
    , 0 AS [Invoice LB], 0 AS [Invoice CWT], 0 AS [Invoice TON]
    , 0 AS [Invoice PC]
    , NULL              AS [Invoice price unit]
    , NULL              AS [Invoice tax]
    , NULL              AS [Invoice tax in trans currency]
    , NULL              AS [Invoice sales amount]
    , NULL              AS [Invoice sales amount in trans currency]
    , NULL              AS [Invoice total unit price]
    , NULL              AS [Invoice total unit price in trans currency]
    , NULL              AS [Invoice additional charges]
    , NULL              AS [Invoice additional charges in trans currency]
    , NULL              AS [Invoice included charges]
    , NULL              AS [Invoice included charges in trans currency]
    , NULL              AS [Invoice non-billable charges]
    , NULL              AS [Invoice non-billable charges in trans currency]
    , NULL              AS [Gross weight charges]
    , NULL              AS [Gross weight charges in trans currency]
    , NULL              AS [Weights charges]
    , NULL              AS [Weights charges in trans currency]
    , NULL              AS [Sales freight charges]
    , NULL              AS [Sales freight charges in trans currency]
    , NULL              AS [Bundle break fee]
    , NULL              AS [Bundle break fee in trans currency];
