{{ config(materialized='view', schema='gold', alias="Sales order line charge fact") }}

SELECT  t.SalesOrderLineChargeKey    AS [Sales order line charge key]
  , t.SalesOrderLineKey          AS [Sales order line key]
  , t.ChargeCategoryKey          AS [Charge category key]
  , t.ChargeCodeKey              AS [Charge code key]
  , t.ChargeCurrencyKey          AS [Charge currency key]
  , t.ChargeTypeKey              AS [Charge type key]
  , t.LegalEntityKey             AS [Legal entity key]
  , t.PricingUOMKey              AS [Pricing UOM key]
  , t.TransDateKey               AS [Trans date key]
  , t.AdditionalCharge           AS [Additional charges]
  , t.AdditionalCharge_TransCur  AS [Additional charges in trans currency]
  , t.TaxAmount                  AS [Charge tax]
  , t.TaxAmount_TransCur         AS [Charge tax in trans currency]
  , t.IncludedCharge             AS [Included charges]
  , t.IncludedCharge_TransCur    AS [Included charges in trans currency]
  , t.IncludeInTotalPrice        AS [Include in total price]
  , t.NonBillableCharge          AS [Non-billable charges]
  , t.NonBillableCharge_TransCur AS [Non-billable charges in trans currency]
  , t.PrintCharges               AS [Print charges]
  , t.TotalCharges               AS [Total charges]
  , t.TotalCharges_TransCur      AS [Total charges in trans currency]
FROM {{ ref("SalesOrderLineCharge_Fact") }} t;
