{{ config(materialized='view', schema='gold', alias="Work order line fact") }}

SELECT  t.WorkOrderLineKey                AS [Work order line key]
  , t.AssetFunctionalLocationKey      AS [Asset functional location key]
  , t.AssetKey                        AS [Asset key]
  , t.InventorySiteKey                AS [Inventory site key]
  , t.ProjectKey                      AS [Project key]
  , t.WorkerKey                       AS [Worker key]
  , t.WorkOrderKey                    AS [Work order key]
  , ISNULL(t.AssetScheduledHours, 0)  AS [Asset schedule hours]
  , ISNULL(t.CapacitySeconds, 0)      AS [Capacity seconds]
  , ISNULL(t.WorkOrderActualHours, 0) AS [Actual hours]
  , NULLIF(t.ActualExpenseCost, 0)    AS [Actual expense cost]
  , NULLIF(t.ActualHourCost, 0)       AS [Actual hour cost]
  , NULLIF(t.ActualItemCost, 0)       AS [Actual item cost]
  , NULLIF(t.CommittedCost, 0)        AS [Committed cost]
  , NULLIF(t.ForecastExpenseCost, 0)  AS [Forecast expense cost]
  , NULLIF(t.ForecastHourCost, 0)     AS [Forecast hour cost]
  , NULLIF(t.ForecastItemCost, 0)     AS [Forecast item cost]
  , NULLIF(t.OriginalBudgetCost, 0)   AS [Original budget cost]
  , NULLIF(t.PurchaseNetAmount, 0)    AS [Purchase net amount]
  , ISNULL(t.ToolScheduledHours, 0)   AS [Tool schedule hours]
  , ISNULL(t.WorkerScheduledHours, 0) AS [Worker schedule hours]
  , t.ScheduleStartDateKey            AS [Schedule start date key]
  , CAST(1 AS INT)                    AS [Work order lines]
FROM {{ ref("WorkOrderLine_Fact") }} t ;
